version: '2'
services:
  mongo:
    image: mongo
    ports:
    - "27017"
  web:
    image: kadirahq/meteord
    volumes:
      - ./bundle:/bundle
    ports:
      - "80:80"
    environment:
      - MONGO_URL=mongodb://mongo:27017/shateo
      - ROOT_URL=http://localhost:80
    links:
      - mongo
