version: '2'
services:
  mongo:
    image: mongo
    ports:
    - "27017"
    entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--rest", "--httpinterface" ]
  mongosetup:
    image: mongo:3.0
    volumes:
      - ./scripts:/scripts
    restart: always
    entrypoint: [ "bash", "/scripts/mongosetup.sh" ]
  web:
    image: danieldent/meteor
    volumes:
      - ./:/
    ports:
      - "80:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/app
      - ROOT_URL=http://localhost:3000
    links:
      - mongo
