version: '2'
services:
  mongo:
    image: mongo
    ports:
    - "27017"
  web:
    image: danieldent/meteor
    volumes:
      - ./:/app
    ports:
      - "80:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/app
      - ROOT_URL=http://localhost:3000
    links:
      - mongo
