version: '2'
services:
  mongo:
    image: mongo
    ports:
    - "27017"
  app:
    build: .
    ports:
        - "3000:3000"
    links:
        - database
    volumes:
        - "./:/src"
    environment:
    - MONGO_URL=mongodb://database:27017/meteor